### ISSUE TITLE
是不是可以加上一个是否打包的配置啊

### ISSUE THREAD

**Issue by vanchKong** [Ssis53/vite-plugin-zip#2]

**Comment by Ssis53** [comment]
插件是在打包完成后开始执行的，应用场景是构建过程中压缩文件，不太懂加上是否打包的配置是什么意思

**Comment by vanchKong** [comment]
> 插件是在打包完成后开始执行的，应用场景是构建过程中压缩文件，不太懂加上是否打包的配置是什么意思

就是加上一个是否生成压缩包的配置项

**Comment by vanchKong** [comment]
> 插件是在打包完成后开始执行的，应用场景是构建过程中压缩文件，不太懂加上是否打包的配置是什么意思

就是加上一个是否生成压缩包的配置项，而不是代码中写上该打包配置，就会在打包时生成压缩包，比如分环境是否生成压缩包

**Comment by Ssis53** [comment]
[completed](https://github.com/Ssis53/vite-plugin-zip/releases/tag/release-1.1.0)

**Comment by vanchKong** [comment]
感谢！！！
