### ISSUE TITLE
可不可以默认打包dist文件夹，然后打包成dist.zip

### ISSUE THREAD

**Issue by qppq54s** [Ssis53/vite-plugin-zip#4]
因为vite默认就是打包到dist文件夹的，这样可以减少使用者的配置

**Comment by Ssis53** [comment]
https://github.com/Ssis53/vite-plugin-zip/releases/tag/2.1.0

**Comment by qppq54s** [comment]
试了下，folderPath和outPath这两个字段还是需要传，感觉也可以使用默认值，需要使用自定义路径时再配置

**Comment by Ssis53** [comment]
> 试了下，folderPath和outPath这两个字段还是需要传，感觉也可以使用默认值，需要使用自定义路径时再配置

麻烦提供下插件的版本号和报错信息

**Comment by qppq54s** [comment]
> > 试了下，folderPath和outPath这两个字段还是需要传，感觉也可以使用默认值，需要使用自定义路径时再配置
> 
> 麻烦提供下插件的版本号和报错信息

我又试了下，发现不配置也可以打包了。之前可能是使用老版本打包了，抱歉抱歉
