### ISSUE TITLE
配合vite-plugin-compression使用问题？

### ISSUE THREAD

**Issue by momtboy** [Ssis53/vite-plugin-zip#6]
未将 vite-plugin-compression 打包压缩后的 .gz文件打入压缩包

**Comment by Ssis53** [comment]
> 未将 vite-plugin-compression 打包压缩后的 .gz文件打入压缩包

vite-plugin-compression插件的执行钩子也是closeBundle，且enforce为'post'，执行的时机是最靠后的，故无法保证其他插件在vite-plugin-compression工作完成后再开始工作，所以无法在同一次构建中以该插件的产物为输入；
如果有需要可以分两次操作。
