### ISSUE TITLE
Can enable to zip without the main folder?

### ISSUE THREAD

**Issue by intositeme** [Ssis53/vite-plugin-zip#7]
In the zip file, it creates a /dist folder. Is it possible to zip all the files from the source folder into the root of the zip file without the /dist?

**Comment by blksmr** [comment]
Hello, i have a opened pull request that provide this feature with `internalDir` #8

**Comment by Ssis53** [comment]
> Hello, i have a opened pull request that provide this feature with `internalDir` #8

Hi, asmirbe.
Thanks for your contribute. But I understand that @intositeme  means that the outermost folder is not needed, rather than removing the inner directory?

**Comment by Ssis53** [comment]
> In the zip file, it creates a /dist folder. Is it possible to zip all the files from the source folder into the root of the zip file without the /dist?

https://github.com/Ssis53/vite-plugin-zip/releases/tag/v3.1.0

**Comment by blksmr** [comment]
Hey @Ssis53
The implementation I provided is quite similar to what you have done.
I understand that you may have had your reasons for implementing it separately, but I believe it would have been more efficient to review and merge my pull request, allowing me to contribute to the project. By collaborating and leveraging the contributions from the community, we can avoid duplication of efforts and foster a more inclusive and efficient development process.
I kindly request that you reconsider merging my pull request, as it has been open for a while and addresses the same functionality. I'm open to any feedback or suggestions you may have to improve my contribution.

**Comment by Ssis53** [comment]
> Hey @Ssis53 The implementation I provided is quite similar to what you have done. I understand that you may have had your reasons for implementing it separately, but I believe it would have been more efficient to review and merge my pull request, allowing me to contribute to the project. By collaborating and leveraging the contributions from the community, we can avoid duplication of efforts and foster a more inclusive and efficient development process. I kindly request that you reconsider merging my pull request, as it has been open for a while and addresses the same functionality. I'm open to any feedback or suggestions you may have to improve my contribution.

Hi @asmirbe 
I am glad to discuss the functional requirements of this project with you. I understand that the requirement of this issuse is to remove the top-level folder, but your implementation removes all directories in the compressed package including the top-level folder, which may be a bit over-designed for this requirement. 
Of course, we can continue to discuss whether it is necessary to add a derivative requirement like add `internalDir` in #8 .
This issues can be closed.
